# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "codemash"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "codemash"
s3_bucket = "cm-..."
s3_prefix = "cm-lambda-deployments"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false
region = "us-west-2"
tags = "codemash:account-id=...,codemash:project-id=..."


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
